source 'https://rubygems.org'
ruby '2.4.1'

# Asset Pipeline Gems
gem 'bourbon',                 '~> 5.0'
gem 'builder',                 '~> 3.2'

# Middleman Core
gem 'middleman',              '~> 4.2'
gem 'middleman-sprockets',    '~> 4.1'
gem 'middleman-aria_current', '~> 0.1'
gem 'middleman-autoprefixer', '~> 2.8'
gem 'middleman-livereload',   '~> 3.4'
gem 'middleman-minify-html',  '~> 3.4'

# Templating Engines
gem 'coffee-script',         '~> 2.4'
gem 'sassc',                 '~>1.11'
gem 'haml',                  '~> 5.0'

# Windows Support
gem 'wdm' if Gem.win_platform?
