source 'https://rubygems.org'
ruby '2.4.1'

# Asset Pipeline Gems
gem 'bourbon',                 '~> 5.0'
gem 'builder',                 '~> 3.2'

# Middleman Core
gem 'middleman',              '~> 4.2'
gem 'middleman-sprockets',    '~> 4.1'
gem 'middleman-aria_current', '~> 0.1'
gem 'middleman-autoprefixer', '~> 2.8'
gem 'middleman-livereload',   '~> 3.4'
gem 'middleman-minify-html',  '~> 3.4'
gem 'middleman-robots',       '~> 1.3'
gem 'middleman-imageoptim',   git: 'https://github.com/plasticine/middleman-imageoptim'
gem 'middleman-seo_sitemap',  git: 'https://github.com/startupheroesuk/middleman-seo_sitemap'

# Templating Engines
gem 'coffee-script',         '~> 2.4'
gem 'sassc',                 '~>1.11'
gem 'haml',                  '~> 5.0'

# Rails Assets
source 'https://rails-assets.org' do
  gem 'rails-assets-jquery',       '~> 1.12.4'
  gem 'rails-assets-normalize-scss', '~> 3.0.3'
end

# Windows Support
gem 'wdm' if Gem.win_platform?
